config/routes.rb
Rails.application.routes.draw do
  get 'songs/create'
  get 'songs/destroy'
  get 'songs/new'
  get 'songs/edit'
  get 'music/destroy'
  get 'privacy_settings/edit'
  get 'privacy_settings/update'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'password_resets/new'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  #get 'users/index'

  resources :users do
    member do
      get :following, :followers, :autocomplete
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :songs
    resources :posts, only: [:create, :destroy]
  resources :posts do
  resource :like, module: :posts
    member do
      post :repost
    end
  end
  resources :relationships, only: [:create, :destroy]

  # Define root url
  root 'home#home'
  # Define routes for Pages
  get '/home' => 'home#home'
  get '/posts/index' => 'posts#index'
  get '/users/:id' => 'home#profile'
  get 'users/:id/following' => 'users#show_following'
  get 'users/:id/followers' => 'users#show_followers'
  get 'users/:id/Music' => 'home#profileMusic'
  get 'posts/:post_id' => 'posts#show'
  get '/explore' => 'home#explore'
  get '/groupies' => 'home#groupies'
  get '/signup' => 'users#new'
  get '/login', to: 'sessions#new'
  get '/settings', to: 'users#edit'
  get'/password_reset', to: 'password_resets#new'
  get'/privacy_settings', to:'privacy_settings#edit'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'users/:id/add_song', to:'songs#new'
  #  get '/livestream' => 'audio#stream'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ActiveRecord::Base
  searchkick text_start: [:username], suggest: [:username]

  def search_data
    {
        name: name,
        username: username,
    }
  end

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest


  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :songs
  has_one_attached :avatar
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: {maximum: 30}
  validates :username, presence: true, length: {maximum: 20}, uniqueness: true
  validates :Terms_of_Agreement, presence: true
  validates :zipcode, presence: true, length: {maximum: 5}
  validates :gender, presence: true
  validates :birthday, presence: true
  validates :bio, length: {maximum: 150}
  validates :avatar, presence: true
  has_secure_password
  validates :password_digest, presence: true, length: {minimum: 6}, allow_nil: true

  has_many :albums
  has_many :albumlikes
  has_many :favorites
  has_many :songs, dependent: :destroy
  has_many :musiclikes
  has_many :pictures
  has_many :posts, dependent: :destroy
  has_many :likes

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    # the cookie
    self.remember_token = User.new_token
    #saving hash of cookie to db
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                        WHERE  follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                        OR user_id = :user_id", user_id: id)
  end

  def likes?(post)
    post.likes.where(user_id: id).any?
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  # Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)

  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [ :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    query = params[:username].presence || "*"
    @users = User.search(query, suggest: true)
  end

  def feed
    Post.where("user_id = ?", id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.account_activation(@user).deliver_now
      #log_in @user
      #flash[:success] = "Success!"
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def show
    @user = User.find(params[:id])
    @post = Post.all.where("user_id = ?", @user)
    @posts = @post.paginate(:page => params[:page], per_page: 6)
    @songs = Song.all
  end

  def edit
    @user = User.find(params[:id])

  end

  def change_password
    @user = User.find_by(email: params[:email])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def autocomplete
    render json: User.search(params[:term], fields: [{username: :text_start}], limit: 10).map(&:username)
  end

  def following
    @title = "following"
    @user = User.find(params[:id])
    @All = Relationship.all.where("follower_id = ?", @user)
    render "show_following"
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @All = Relationship.all.where("followed_id = ?", @user)
    render "show_followers"
  end



  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :name, :zipcode, :bio,
                                 :gender, :password, :password_confirmation,
                                 :birthday, :Terms_of_Agreement, :avatar)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.activated?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary btn-sm" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-sm" %>
<% end %>

app/views/users/change_password.html.erb
<% if logged_in? %>
  <% provide(:title, "Edit user") %>
  <div class="container settings_center">
    <div class="left_settings">
      <h1> Settings</h1>
      <ul>
        <li>Edit Profile</li>
        <li>Change Password</li>
        <li>Privacy and Security</li>
      </ul>
    </div>

    <div class="right_settings">
      <%= form_for @user do |f| %>
        <%= f.label :password, class: "vibin_form_text" %>
        <%= f.text_field :password, class: "form-control" %>

        <%= f.label :password_confirmation, class: "vibin_form_text" %>
        <%= f.text_field :password_confirmation, class: "form-control" %>
        <%= f.submit "Save changes", class: "btn btn-primary vibin_btn" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if logged_in? %>
  <% provide(:title, "Edit user") %>
  <div class="container forall settings_center">
    <div class="left_settings">
      <center><h1> Settings</h1></center>
      <ul>
        <li>
          <%= link_to 'Edit Profile', edit_user_url(current_user.id), :class => "nav-link" %>
        </li>
        <li>
        </li>
        <li>
          <%= link_to 'Privacy and Security','/privacy_settings', :class =>  "nav-link" %>
        </li>
        <li><%= link_to "deactivate", @user, method: :delete, data: {confirm: "You sure?"} %></li>
      </ul>


    </div>

    <div class="right_settings">
      <br/>
      <%= form_for @user do |f| %>
      <br/><br/>
        <%= f.file_field :avatar, class: "btn btn-sm  photo_upload ml-5 ", style: "width:10%;" %>

 <br/>
        <%= f.label :name, class: "vibin_form_text ml-5" %>
        <%= f.text_field :name, class: "form-control ml-5 ", style: "width:80%;" %>

        <%= f.label :username, class: "vibin_form_text ml-5" %>
        <%= f.text_field :username, class: "form-control ml-5", style: "width:80%;" %>

        <%= f.label :bio, class: "vibin_form_text ml-5" %>
        <%= f.text_area :bio, class: "form-control ml-5", style: "width:80%;" %>

        <%= f.label :zipcode, class: "vibin_form_text ml-5" %>
        <%= f.number_field :zipcode, class: "form-control ml-5", style: "width:80%;" %>

        <%= f.submit "Save changes", class: "btn btn-primary vibin_btn" %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/users/index.html.erb
<div class="container forall">
  <% if @users.suggestions.any? %>
      Did you mean: <%= @users.suggestions.first %>
  <% end %>
  <% @users.each do |user| %>
<div>
    <p><%= user.username %></p>
</div>
<% end %>
</div>

app/views/users/new.html.erb
<div class="container forall border border-dark">
  <center><h1>Sign up</h1></center>
  <%= form_for(@user) do |f| %>
    <div class="row signup border border-dark">
      <%= f.label :email, style: "margin-right: 36px;" %>
      <%= f.email_field :email %>
    </div>
    <div class="row signup">
      <%= f.label :username, style: "margin-right: 32px;" %>
      <%= f.text_field :username %>
    </div>
    <div class="row signup">
      <%= f.label :name, style: "margin-right: 32px;" %>
      <%= f.text_field :name %>
    </div>
    <div class="row signup">
      <%= f.label :zipcode, style: "margin-right: 32px;" %>
      <%= f.number_field :zipcode %>
    </div>
    <div class="row signup">
      <%= f.label :gender, style: "margin-right: 32px;" %>
      <%= f.select(:gender, ["Male", "Female"]) %>
    </div>
    <div class="row signup">
      <%= f.label :password, style: "margin-right: 5px;" %>
      <%= f.password_field :password %>
    </div>
    <div class="row signup">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="row signup">
      <%= f.label :birthday, style: "margin-right: 32px;" %>
      <%= f.date_select :birthday, order: [:month, :day, :year],
                        prompt: {day: 'Select day', month: 'Select month', year: 'Select year'},
                        start_year: Date.today.year - 5, end_year: Date.today.year - 120 %></div>

    <div class="row signup">
      <%= f.check_box :Terms_of_Agreement, style: "margin-top: 5px; margin-right:5px" %>
      <%= f.label :Terms_of_Agreement, "I accept the Terms of Agreement" %>
    </div>
    <div class="row signup">
      <%= f.file_field :avatar, style: "margin-top: 5px; margin-right:5px" %>
    </div>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>


</div>

app/views/users/show.html.erb
<!-- remove all borders -->


<% if logged_in? %>
  <div class="container-fluid forall border border-warning border-thick" style="min-width:1000px;">
    <div class="row justify-content-center border border-primary border-thick " style="height:300px;">

      <img src="/galaxy.jpg" style="left:0px; width:50%; height: 300px; top:0px; z-index:-1; position:absolute;">
      <img src="/tree.jpg" style="left:50%; width:50%; height: 300px; top:0px; z-index:-1; position:absolute;">
      <p class="user-profile-name">
        <span class="badge badge-primary text-white" style="height:20px;"><%= @user.name %></span></p>
      <p class="user-profile-username">
        <span class="badge badge-primary text-white" style="height:20px;">@<%= @user.username %></span></p>
      <p class="user-profile-location">
        <span class="badge badge-primary text-white" style="height:20px;"><%= @user.zipcode %></span></p>
      <div class="profile-avatar">
        <% if @user.avatar != nil %>
          <%= image_tag (@user.avatar), style: "width:100px; height:100px; object-fit:cover;" %>
        <% else %>
          <img src="/default-avatar.jpg" style="width:100px; height:100px; object-fit:cover;">
        <% end %>
      </div>
      <div class="favorite-artist">
        <center>
          <h3><span class="badge badge-secondary">Favorite Artist</span></h3><br>
          <h4><a href="#" class="badge badge-primary" style="line-height:10px; transform: translateY(-40px);">
            Currensy</a></h4>
        </center>
      </div>

      <div class="favorite-song">
        <center><h3><span class="badge badge-secondary"> Favorite Song</span></h3><br>
          <h4>
            <a href="#" class="badge badge-primary" style="line-height:10px; transform: translateY(-40px); "> JUICE WRLD
              - LUCID DREAM</a></h4></center>
      </div>
      <div class="followers">
        <span class="badge badge-secondary">   Followers </span><br>
        <h4><%= link_to @user.followers.count, followers_user_path(@user), :class => "badge badge-primary", :style => "line-height:10px; color:white; transform: translate(20px,-7px);" %></a></h4>
      </div>
      <div class="following">
        <span class="badge badge-secondary">   Following </span><br>
        <h4><%= link_to @user.following.count, following_user_path(@user), :class => "badge badge-primary", :style => "line-height:10px; color:white; transform: translate(20px,-7px);" %></a></h4>
      </div>
      <div class="bio">
        <span class="badge badge-success" style="width: 300px; height:auto;"> <%= @user.bio %></span>
      </div>

    </div>


    <div class="row bg-success " >
      <ul class="nav nav-tabs " id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="Posts-tab" data-toggle="tab" href="#Posts" role="tab" aria-controls="Posts" aria-selected="true">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="Music-tab" data-toggle="tab" href="#Music" role="tab" aria-controls="Music" aria-selected="false">Music</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="Playlists-tab" data-toggle="tab" href="#Playlists" role="tab" aria-controls="Playlists" aria-selected="false">Playlists</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="Media-tab" data-toggle="tab" href="#Media" role="tab" aria-controls="Media" aria-selected="false">Media</a>
        </li>
        <li class="nav-item">
         <!-- <a class="nav-link" id="AddMusic-tab" data-toggle="tab" href="#AddMusic" role="tab" aria-controls="AddMusic" aria-selected="false">Add Music</a>
         -->
          <%= link_to "Add Music", new_song_url %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mr-2">
          <%= render 'follow_form' if logged_in? %>
        </li>

      </ul>
    </div>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="Posts" role="tabpanel" aria-labelledby="Posts-tab"><%= render "posts/userfeed" %></div>
        <div class="tab-pane fade" id="Music" role="tabpanel" aria-labelledby="Music-tab"><%= render "songs/show_music" %></div>
        <div class="tab-pane fade" id="Playlists" role="tabpanel" aria-labelledby="Playlists-tab">.3..</div>
        <div class="tab-pane fade" id="Media" role="tabpanel" aria-labelledby="Media-tab"><%= render "posts/PhotosOnly" %></div>
        <div class="tab-pane fade" id="AddMusic" role="tabpanel" aria-labelledby="AddMusic-tab"><%= link_to %></div>
      </div>

    <div class="row" style="height:90px;">
      <div class="col footer">
        <center><p>Vibin Music inc. BITCH</p></center>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show_followers.html.erb
<div class="container-fluid forall border" style="min-width: 850px;">
<% provide(:title, @title) %>
  <div class="row border border-success ">
    <div class="col-md-8">
      <h3><%= @title %></h3>
        <div class="user_avatars">
          <% for @p in @All %>
          <div class="row border border-success">
            User id: <%= link_to @p.follower_id, user_path(@p.follower_id) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show_following.html.erb
<div class="container-fluid forall border" style="min-width: 850px;">
<% provide(:title, @title) %>
  <div class="row border border-success">
    <div class="col-md-8">
      <h3><%= @title %></h3>
           <div class="user_avatars">
             <% for @p in @All %>
               <div class="row border border-success">
                 User id: <%= link_to @p.followed_id, user_path(@p.followed_id) %>
              </div>
             <% end %>
           </div>
    </div>
  </div>
</div>