config/routes.rb
Rails.application.routes.draw do
  get 'songs/create'
  get 'songs/destroy'
  get 'songs/new'
  get 'songs/edit'
  get 'music/destroy'
  get 'privacy_settings/edit'
  get 'privacy_settings/update'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'password_resets/new'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  #get 'users/index'

  resources :users do
    member do
      get :following, :followers, :autocomplete
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :songs
    resources :posts, only: [:create, :destroy]
  resources :posts do
  resource :like, module: :posts
    member do
      post :repost
    end
  end
  resources :relationships, only: [:create, :destroy]

  # Define root url
  root 'home#home'
  # Define routes for Pages
  get '/home' => 'home#home'
  get '/posts/index' => 'posts#index'
  get '/users/:id' => 'home#profile'
  get 'users/:id/following' => 'users#show_following'
  get 'users/:id/followers' => 'users#show_followers'
  get 'users/:id/Music' => 'home#profileMusic'
  get 'posts/:post_id' => 'posts#show'
  get '/explore' => 'home#explore'
  get '/groupies' => 'home#groupies'
  get '/signup' => 'users#new'
  get '/login', to: 'sessions#new'
  get '/settings', to: 'users#edit'
  get'/password_reset', to: 'password_resets#new'
  get'/privacy_settings', to:'privacy_settings#edit'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'users/:id/add_song', to:'songs#new'
  #  get '/livestream' => 'audio#stream'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many :posts #, inverse_of: :songs
  validates :title, presence: true, length: {maximum: 40}
  validates :text, length: {maximum: 100}
  validates :genre, presence: true
  has_one_attached :song_file
  validates :song_file, presence: true
  validate :correct_file_type?

  private

  def correct_file_type?
    if song_file.attached? && !song_file.content_type.in?(%w(audio/mp3 audio/mp4 audio/mpeg))
      errors.add(:song_file, 'Must be an AUDIO file!')
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :music]
  # before_action :correct_user, only: [:create, :destroy]
  before_action :set_song, only: [:show]

  def create
    puts "112233"
    @song = current_user.songs.new(song_params)
    if (@song.save!)
      puts "wild"
      @post = current_user.posts.new(post_params.merge(song_id: @song.id))
      if @post.save!
        redirect_to root_url
      end
    else
      render :new
    end
  end

  def edit
  end

  def new
    @song = Song.new

  end

  def destroy
  end

  def show
    @song = Song.find(params[:id])
  end

  def music
    @songs = Songs.all
    render "show_music"
  end

  def show_music
    @songs = Song.all

  end

  private

  def song_params
    params.require(:song).permit(:title, :text, :genre, :song_file, :user_id)

  end

  def set_song
    @song = Song.find(params[:id])
  end

  def post_params
    params.permit(:text)
  end

  def correct_user
    redirect_to(root_url) unless current_user?(@user)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_show_music.html.erb
<center><%= current_user.name %>'s Songs</center>
<hr>
<% for @song in @songs %>
  <ul style="list-style-type:none">

  </ul>
  <h3><b><%= @song.title %></b></h3>
  <h5><%= @song.text %></h5>
  <hr>
<% end %>

app/views/songs/create.html.erb
<h1>Songs#create</h1>
<p>Find me in app/views/songs/create.html.erb</p>

app/views/songs/destroy.html.erb
<h1>Songs#destroy</h1>
<p>Find me in app/views/songs/destroy.html.erb</p>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<div class="container forall">
  <div class="row">
    <div class="col">
        Hi
    </div>
  </div>
</div>

app/views/songs/new.html.erb
<div class="container forall border border-dark">
 <center> <h1> Go ahead and upload your Song! </h1></center>
  <%= form_for(@song) do |f| %>
    <div class="row signup">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title %>
    </div>

    <div class="row signup">
      <%= f.label :text, "Text" %>
      <%= f.text_field :text %>
    </div>

    <div class="row signup">
      <%= f.label :genre, "Genre" %>
      <%= f.select :genre, ['Pop', 'Rap', 'Jazz', 'Other'] %>
    </div>

    <div class="row signup">
      <%= f.label :song_file, "Upload Song File" %>
      <%= f.file_field :song_file %>
    </div>

    <%= f.submit "Add Music", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/songs/show.html.erb
<div class="container forall" >
  <div class="row">
    <div class="col">
      <%= @song.context %>
      <%= link_to "Song", @song.song_file, :class => "html5" %>

      <div class="row" ><p id="demo"></p></div>
      <section id="audio" >

      </section>
    </div>
  </div>
</div>
<script>
    function play() {

      var audioSection = $('section#audio');

          var audio = $('<audio>', {
              controls: 'controls',
              autoplay: 'autoplay'
          });
          var song_path = "<%= @song.song_file%>";
          document.getElementById("demo").innerHTML = song_path;
          var url = "/assets/Lil.mp3";
          $('<source>').attr('src', url).appendTo(audio);
          audioSection.html(audio);
          return false;

    }
    $(document).ready(function () {
        var audioSection = $('section#audio');
        $('a.html5').click(function () {
            var audio = $('<audio>', {
                controls: 'controls',
                autoplay: 'autoplay'
            });
            var url = $(this).attr('href');
            document.getElementById("")
            $('<source>').attr('src', url).appendTo(audio);
            audioSection.html(audio);
            return false;
        });
    });
</script>