config/routes.rb
Rails.application.routes.draw do
  get 'songs/create'
  get 'songs/destroy'
  get 'songs/new'
  get 'songs/edit'
  get 'music/destroy'
  get 'privacy_settings/edit'
  get 'privacy_settings/update'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'password_resets/new'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  #get 'users/index'

  resources :users do
    member do
      get :following, :followers, :autocomplete
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :songs
    resources :posts, only: [:create, :destroy]
  resources :posts do
  resource :like, module: :posts
    member do
      post :repost
    end
  end
  resources :relationships, only: [:create, :destroy]

  # Define root url
  root 'home#home'
  # Define routes for Pages
  get '/home' => 'home#home'
  get '/posts/index' => 'posts#index'
  get '/users/:id' => 'home#profile'
  get 'users/:id/following' => 'users#show_following'
  get 'users/:id/followers' => 'users#show_followers'
  get 'users/:id/Music' => 'home#profileMusic'
  get 'posts/:post_id' => 'posts#show'
  get '/explore' => 'home#explore'
  get '/groupies' => 'home#groupies'
  get '/signup' => 'users#new'
  get '/login', to: 'sessions#new'
  get '/settings', to: 'users#edit'
  get'/password_reset', to: 'password_resets#new'
  get'/privacy_settings', to:'privacy_settings#edit'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'users/:id/add_song', to:'songs#new'
  #  get '/livestream' => 'audio#stream'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
  belongs_to :song, optional: true
  has_many_attached :image1
  has_one_attached :image2
  has_one_attached :image3
  has_one_attached :image4
  has_one_attached :avatar
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :context, presence: true unless :song_id
  validates :image1, presence: false
  has_many :likes
  has_many :image1
  # has_many :songs
  has_many :comments, dependent: :destroy
  # has_many :songs, inverse_of: :post, dependent: :destroy
  #  accepts_nested_attributes_for :songs, reject_if: proc { |attributes| attributes[:name].blank?}, allow_destroy: true


  def post_type
    if post_id? && context?
      "repost"
    elsif post_id?
      "repost"
    elsif song_id?
       "song"
    else
       "post"
    end
  end


end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
before_action :logged_in?
before_action :set_post

 def create
   @post.likes.where(user_id: current_user.id).first_or_create

   respond_to do |format|
     format.html {redirect_to @post}
     format.js
   end
 end

 def destroy
@post.likes.where(user_id: current_user.id).destroy_all

respond_to do |format|
  format.html {redirect_to @post}
  format.js
end
 end

 private
    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in?, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  before_action :set_post, only: [:show, :edit, :update, :destroy, :repost]
def new
  @post = Post.new
end

def index
  @posts = Post.all
end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created."}
        format.json { render :show, status: :created, location: @post}
      else
        format.html { redirect_to :new}
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
  end
end

def update
   respond_to do |format|
     if @post.update(post_params)
       format.html { redirect_to @post, notice: 'Tweet was successfully updated.' }
       format.json { render :show, status: :ok, location: @post}
     else
       format.html { render :edit }
       format.json { render json: @post.errors, status: :unprocessable_entity }
     end
   end
 end




def repost
  post = current_user.posts.new(post_id: @post.id, context: @post.context)
  # error is right here ^
  if post.save!
    redirect_to root_url
  else
    redirect_to :back, alert: "Unable to repost"
  end
end

#
#def repost
#  @error = true;
#  begin
#    post = current_user.posts.new(post_id: @post.id)
#    if post.save!
#      redirect_to root_url
#      @error = false;
#    else
#      raise
#      redirect_to root_url, alert: "Unable to repost"
#    end
#  rescue Exception => e
#    puts "ERROR---------------------\n #{e}"
#  ensure
#    if error
#      redirect_to root_url, alert: "Unable to repost"
#    else
#      redirect_to root_url
#    end
#  end
#end


  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end

  def show
    @user = User.find(@post.user_id)
  end


  private

  def post_params
    params.require(:post).permit(:user_id, :context, :post_id, image1: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def image_preview(f)
    url, style = f.object.avatar.present? ? [f.object.avatar, 'height:70px; width: 70px;'] : ['#', 'left: 100px; '] #just do this in a CSS file
    content_tag(:div, nil) do
      concat image_tag url, {id: 'preview_image', style: style}
      concat ''.html_safe
      concat f.button 'Remove', {type: 'button', class: 'remove_image', style: 'display:none;'}
    end
  end
end

app/views/posts/_PhotosOnly.html.erb
<% @posts.each do |post| %>
    <% if post.image1[0].presence %>
    <div class="row post border border-primary" style="cursor: pointer;">
      <div class="col-xs-3 border border-warning justify-content-center text-center " style="width:18%;">
        <%= image_tag (post.user.avatar), class:"post-ava" if post.user.avatar != nil %>
          <span class="badge badge-primary" style="width:100%;"><%= User.find(post.user_id).name %></span>
          <span><%= link_to "@"+User.find(post.user_id).username, user_path(post.user_id), class: "badge badge-primary", style: "width:100%;"%></span>
          <br/>
          <br/>
      </div>
      <div class="col-xs-6 border border-danger " style="width:70%;" >
        <br/>
        <p style="margin-left:10px;"><%= post.context %></p>
        <% if post.image1[0].presence %>
        <div class="row img-wrapper img-post" style="margin-left: 30px;">
             <%= image_tag (post.image1[0]), style: "height:120%; object-fit:cover; width:100%; display: inline-block; overflow: hidden;" %>
           </div>
        <% end %>
        <% if post.image1[1].presence %>
        <div class="row img-wrapper img-post" style="margin-left: 30px;">
             <%= image_tag (post.image1[1]), style: "height:120%; object-fit:cover; width:100%; display: inline-block; overflow: hidden;" %>
           </div>
        <% end %>
      </div>
      <div class="col-xs-2  ml-auto border border-dark " style="width: 10%;">
        <% if post.user_id != current_user.id %>
        <%= link_to "Repost", repost_post_path(post), method: :post%>
            <p id="post_<%= post.id %>_likes"><%= render partial: "/posts/likes", locals: {post: post} %></p>
        <% end %>
        <p style="font-size:8px; float:right;"><%= post.updated_at %></p>
      </div>
    </div>


    <% end %>
<% end %>

<%= will_paginate @posts %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<center><br/><div class="row" style="">
    <%= f.text_area :context, class:"", style: "background-color: transparent; overflow:hidden; display:block; border-radius:5px; border:3px solid green;", rows: "1", placeholder: "Text" %>
  </div></center>
   <!-- photo button -->
  <div class="row">
    <div class="col-xs-3">
      <label class="btn btn-primary btn-sm">
        <%= image_tag "PictureUploadButton.png", style: "height:20px; width:20px;" %>
      <span style="display:none;" class="">
          <%= f.file_field :image1, id:"image1", multiple: true,  accept: 'image/png, image/jpeg' %>
        </span>
      </label>
     </div>
     <div class="ovaa hidden col-xs-3 border border-primary ml-auto" style="width: 80px; max-height:80px;" id="imagediv">
        <%= image_tag "", id: "image", style: "width:80px; height: 80px;"%>
     </div>
  </div>
<!-- song button -->
  <div class="row">
    <div class="col-xs-3">
      <label class="btn btn-primary btn-sm">
        <%= image_tag "MusicButton.png", style: "height:20px; width:20px;" %>
      <span style="display:none;" class="">
      <%= f.fields_for :songs do |g|%>
      <%= g.file_field :song_file%>
      <% end %>
      </span>
    </label>
    </div>
  </div>
<!-- post button -->
  <div class="row">
    <div class="col-xs-3">
      <label class="btn btn-primary btn-sm">
        <%= image_tag "PostButton.png", style: "height:20px; width:20px;" %>
        <span style="display:none;" class="">
          <%= f.submit "", style:"width: 50px; height:20px;"%>
        </span>
      </label>
     </div>
  </div>
<% end %>
<button > Expand post</button>



<script>
  document.addEventListener('input', function (event) {
	   if (event.target.tagName.toLowerCase() !== 'textarea') return;
	    autoExpand(event.target);
  }, false);
  var autoExpand = function (field) {

	// Reset field height
	field.style.height = 'inherit';

	// Get the computed styles for the element
	var computed = window.getComputedStyle(field);

	// Calculate the height
	var height = parseInt(computed.getPropertyValue('border-top-width'), 10)
	             + parseInt(computed.getPropertyValue('padding-top'), 10)
	             + field.scrollHeight
	             + parseInt(computed.getPropertyValue('padding-bottom'), 10)
	             + parseInt(computed.getPropertyValue('border-bottom-width'), 10);

	field.style.height = height + 'px';

};

document.getElementById("image1").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image").src = e.target.result;
        document.getElementById("imagediv").classList.remove("hidden");
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};



</script>

app/views/posts/_likes.html.erb
<% if logged_in? && current_user.likes?(post) %>
<%= link_to "Unlike", post_like_path(post), class: "btn btn-info btn-sm buticons glyphicon glyphicon-fire", method: :delete, remote: true %>
<% else %>
<%= link_to "Like", post_like_path(post), class: "btn btn-info btn-sm buticons glyphicon glyphicon-fire",method: :post, remote: true %>
<% end %>
<%= post.likes.count %>

app/views/posts/_post.html.erb
  <div class="row post border border-primary" style="cursor: pointer;">
    <div class="col-xs-3 border border-warning justify-content-center text-center " style="width:18%;">
      <%= image_tag (post.user.avatar), class:"post-ava" if post.user.avatar != nil %>
        <span class="badge badge-primary" style="width:100%;"><%= User.find(post.user_id).name %></span>
        <span><%= link_to "@"+User.find(post.user_id).username, user_path(post.user_id), class: "badge badge-primary", style: "width:100%;"%></span>
        <br/>
        <br/>
    </div>
    <div class="col-xs-6 border border-danger " style="width:70%;" >
      <br/>
      <p style="margin-left:10px;"><%= post.context %></p>
      <div class="row justify-content-center">
      <% if post.image1[0].presence %>
      <div class="col-xs-3 img-wrapper img-post" style="margin-left: 30px;">
           <%= image_tag (post.image1[0]), style: "height:105%; object-fit:cover; width:105%; display: inline-block; overflow: hidden;", class:"imageclass" %>
         </div>
      <% end %>
      <% if post.image1[1].presence %>
      <div class="col-xs-3 img-wrapper img-post" style="margin-left: 30px;">
           <%= image_tag (post.image1[1]), style: "height:105%; object-fit:cover; width:105%; display: inline-block; overflow: hidden;" %>
         </div>
      <% end %>
    </div>
  </div>
    <div class="col-xs-2  ml-auto border border-dark " style="width: 10%;">
      <% if post.user_id != current_user.id %>
      <%= link_to "Repost", repost_post_path(post), method: :post%>
          <p id="post_<%= post.id %>_likes"><%= render partial: "/posts/likes", locals: {post: post} %></p>
      <% end %>
      <p style="font-size:8px; float:right;"><%= post.updated_at %></p>
    </div>
  </div>

app/views/posts/_repost.html.erb
  <div>Reposted by <%= post.user.username %></div>
  <%= render partial: "posts/post", locals: (post: post.post)%>
  </div>

app/views/posts/_song.html.erb
<div class="row post border border-primary" style="cursor: pointer;">
  <div class="col-xs-3 border border-warning justify-content-center text-center " style="width:18%;">
    <%= image_tag (post.user.avatar), class: "post-ava" if post.user.avatar != nil %>
    <span class="badge badge-primary" style="width:100%;"><%= User.find(post.user_id).name %></span>
    <span><%= link_to "@" + User.find(post.user_id).username, user_path(post.user_id), class: "badge badge-primary", style: "width:100%;" %></span>
    <br/>
    <br/>
  </div>
  <div class="col-xs-6 border border-danger " style="width:70%;">
    <br/>
    <% @song = Song.find(post.id) %>
    <h1 style="margin-left:15%; margin-right: 15%;"><%= @song.title %></h1>
    <h5 style="margin-left:10px;"><b>Genre:</b><i> <%= @song.genre %></i></h5>
     <p style="margin-left:10px; margin-top:20px"><%= @song.text %></p>
    <div class="row justify-content-center">
      <% if post.image1[0].presence %>
        <div class="col-xs-3 img-wrapper img-post" style="margin-left: 30px;">
          <%= image_tag (post.image1[0]), style: "height:105%; object-fit:cover; width:105%; display: inline-block; overflow: hidden;", class: "imageclass" %>
        </div>
      <% end %>
      <% if post.image1[1].presence %>
        <div class="col-xs-3 img-wrapper img-post" style="margin-left: 30px;">
          <%= image_tag (post.image1[1]), style: "height:105%; object-fit:cover; width:105%; display: inline-block; overflow: hidden;" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-xs-2  ml-auto border border-dark " style="width: 10%;">
    <% if post.user_id != current_user.id %>
      <%= link_to "Repost", repost_post_path(post), method: :post %>
      <p id="post_<%= post.id %>_likes"><%= render partial: "/posts/likes", locals: {post: post} %></p>
    <% end %>
    <p style="font-size:8px; float:right;"><%= post.updated_at %></p>
  </div>
</div>

app/views/posts/_userfeed.html.erb
<% @posts.each do |post| %>
    <%= render partial: "posts/#{post.post_type}", locals: {post: post}%>
<% end %>

<%= will_paginate @posts %>

app/views/posts/index.html.erb
<br/>
<br/>
<h1>Posts</h1>

<% @posts.each do |post| %>
<div class="row">
  <%= render partial: "posts/#{post.post_type}", locals: {post: post} %>
</div>
<% end %>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1> New Post </h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container forall">

  <div class="row post border border-primary">
    <div class="col-xs-3 border border-warning " style="width:20%;">

        <%= image_tag (@user.avatar), class:"post-img" %>
        <span class="badge badge-primary"><%= User.find(@post.user_id).name %></span>
        <br/>
        <span class="badge badge-primary">@<%= link_to User.find(@post.user_id).username, user_path(@post.user_id), style: "color:white;" %></span>
    <br/>
      <div class="row">
        <div class="col">

     </div></div>
   </div>

    <div class="col-xs-6 border border-danger " style="width: 60%;"  >
  <br/>
  <div class="row" style="margin-left: 30px;">
       <p><%= @post.context %></p> <!-- DO A MIGRATE WHEN YOU HAVE A CHANCE - Alex @ 10:47pm Dec 29-->
     </div>
     <br/> <br/>


     <% if @post.image1[0].presence %>
     <div class="row img-wrapper img-post" style="margin-left: 30px;">
          <%= image_tag (@post.image1[0]), style: "height:120%; object-fit:cover; width:100%; display: inline-block; overflow: hidden;" %>

        </div>
     <% end %>
     <% if @post.image1[1].presence %>
     <div class="row img-wrapper img-post" style="margin-left: 30px;">
          <%= image_tag (@post.image1[1]), style: "height:120%; object-fit:cover; width:100%; display: inline-block; overflow: hidden;" %>
        </div>
     <% end %>

    </div>
  <div class="col-xs-2" >
    <% if @post.user_id != current_user.id %>
       <%= render partial: "posts/#{post.post_type}", locals: {post: @post}%>
       <br/>
       <p id="post_<%= @post.id %>_likes"><%= render partial: "/posts/likes", locals: {post: @post} %></p>
    <% end %> <br/> <br/> <br/> <br/> <br/>
      <p><%= @post.updated_at %></p>
      <%= link_to "delete", @post, method: :delete,
                                             data: { confirm: "You sure?" } %>
  </div>


  </div>
</div>