config/routes.rb
Rails.application.routes.draw do
  get 'songs/create'
  get 'songs/destroy'
  get 'songs/new'
  get 'songs/edit'
  get 'music/destroy'
  get 'privacy_settings/edit'
  get 'privacy_settings/update'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'password_resets/new'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  #get 'users/index'

  resources :users do
    member do
      get :following, :followers, :autocomplete
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :songs
    resources :posts, only: [:create, :destroy]
  resources :posts do
  resource :like, module: :posts
    member do
      post :repost
    end
  end
  resources :relationships, only: [:create, :destroy]

  # Define root url
  root 'home#home'
  # Define routes for Pages
  get '/home' => 'home#home'
  get '/posts/index' => 'posts#index'
  get '/users/:id' => 'home#profile'
  get 'users/:id/following' => 'users#show_following'
  get 'users/:id/followers' => 'users#show_followers'
  get 'users/:id/Music' => 'home#profileMusic'
  get 'posts/:post_id' => 'posts#show'
  get '/explore' => 'home#explore'
  get '/groupies' => 'home#groupies'
  get '/signup' => 'users#new'
  get '/login', to: 'sessions#new'
  get '/settings', to: 'users#edit'
  get'/password_reset', to: 'password_resets#new'
  get'/privacy_settings', to:'privacy_settings#edit'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'users/:id/add_song', to:'songs#new'
  #  get '/livestream' => 'audio#stream'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def nav
        @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:users).permit(:id, :full_name, :email)
    end
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/layouts_helper.rb
module LayoutsHelper

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
end
end 

app/views/layouts/_nav.html.erb
<% if logged_in? %>
  <%= render '/layouts/nav_user' %>
  <% else %>
    <%= render '/layouts/nav_guest' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-expand navbar-dark " style="background-color: #00e699; position: fixed; min-width: 1000px; width: 100%; z-index:999;">
    <a class="navbar-brand" href="/">Vibin Music</a>
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav pt-1">
            <li class="nav-item">
                <a class="nav-link" href="/explore">Explore</a>
            </li>
            <li><a class="nav-link" href="/signup"> Sign up </a></li>
            <li><a class="nav-link" href="/login">Log in</a></li>
<!--hi check the chat-->



        </ul>
    </div>
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-expand navbar-dark bg-success" style="position: fixed; width: 100%; min-width:700px; z-index:999; height:50px;">
    <a class="navbar-brand" style="font-size:20px;" href="/home">Vibin Music</a>
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav pt-1">
            <li class="nav-item">
                <a class="nav-link" href="/explore">Explore</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">Notifications </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/groupies">Groupies</a>
            </li>
            <li class="nav-item">
              <%= link_to 'Profile', user_path(current_user) , :class =>  "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to'Log Out',logout_path, method: :delete, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= form_tag users_path, method: :get do %>
                <%= text_field :username, nil %>
                <% end %>
            </li>

        </ul>

    </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>VibinMusicBeta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js' %>
  </head>


  <body  onload="play()">
  <%= render '/layouts/nav' %>
  <div class="container">
    <div class="row">
      <div class="col">

      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

  </body>
</html>